// Rebuilds precache.js and files.json from the files on disk (sizes + content hashes).
// Run from the project root after changing or adding runtime files:   node guide/tools/update_precache.mjs
// New runtime files: add them to EXTRA below (or to the list in precache.js) so preload.js caches them.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import vm from 'node:vm';

const EXTRA = ['ghosts.js'];
const sandbox = { self: {} };
vm.runInNewContext(readFileSync('precache.js', 'utf8'), sandbox);
const old = sandbox.self.AETHER_PRECACHE;
const paths = [...old.files.map(f => f[0])];
for (const p of EXTRA) if (!paths.includes(p)) paths.splice(Math.max(0, paths.indexOf('game.js')), 0, p);

const hash = buf => createHash('sha1').update(buf).digest('hex').slice(0, 12);
const files = [], missing = [];
for (const p of paths) {
  if (!existsSync(p)) { missing.push(p); continue; }
  const buf = readFileSync(p);
  files.push([p, buf.length, hash(buf)]);
}
if (missing.length) console.warn('Skipped missing files:', missing.join(', '));
const total = files.reduce((n, f) => n + f[1], 0);
const version = hash(Buffer.from(files.map(f => f[2]).join('')));
writeFileSync('precache.js', '/* Generated by guide/tools/update_precache.mjs: runtime files [path, bytes, sha1] for preload.js and sw.js. Do not edit. */\n'
  + 'self.AETHER_PRECACHE = ' + JSON.stringify({ version, total, files }) + ';\n');

const listed = [...files.map(f => f[0]), 'precache.js', 'sw.js'];
const list = listed.filter(existsSync).map(file => ({ file, bytes: readFileSync(file).length }));
writeFileSync('files.json', JSON.stringify({ files: list.length, bytes: list.reduce((n, f) => n + f.bytes, 0), list }, null, 2) + '\n');
console.log(`precache.js: ${files.length} files, ${(total / 1048576).toFixed(1)} MB, version ${version}`);
